version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build started on `date`
      - java -version
      - mvn package shade:shade
      - mv target/AWSLambda-1.0-SNAPSHOT.jar .
      - unzip AWSLambda-1.0-SNAPSHOT.jar
      - ls
      - rm -rf target src logs buildspec.yml pom.xml AWSLambda-1.0-SNAPSHOT.jar
      - aws cloudformation package --template-file template.yml --s3-bucket lambdaprojekt --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
  - outputtemplate.yml
  - template.yml

