version: 0.2
phases:
build:
  commands:
    – echo Build started on `date`
    # Unit tests, Code analysis and dependencies check (maven lifecycle phases: validate, compile, test, package, verify)
    – mvn verify shade:shade -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=error
    – mv target/MyApp-1.0.jar .
    – unzip MyApp-1.0.jar
    – rm -rf target tst src buildspec.yml pom.xml MyApp-1.0.jar
    – aws cloudformation package –template-file template.yaml –output-template-file transformed_main.yaml -–s3-bucket lambdaprojekt
cache:
paths:
  – ‘/root/.m2/**/*’
artifacts:
type: zip
files:
  – transformed_main.yaml