AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS lambda deployment
Resources:
  CurrencyExchange:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambdas.ScheduledHandler::handleRequest
      Runtime: java11
      CodeUri: s3://lambdaprojekt/c25bad194c949ecfb8d6ed7ae9f543f0
      MemorySize: 512
      Timeout: 45
      Role: arn:aws:iam::542069312762:role/lambdaDeploy-CurrencyExchangeRole-1C6ESYKMP459V
